<?php

namespace FondOfSpryker\Zed\CategoryStoreStorage\Communication;

use Spryker\Zed\CategoryStorage\Communication\CategoryStorageCommunicationFactory as SprykerCategoryStorageCommunicationFactory;

class CategoryStoreStorageCommunicationFactory extends SprykerCategoryStorageCommunicationFactory
{

}
