<?php

namespace FondOfSpryker\Zed\CategoryStoreStorage\Persistence;

use Spryker\Zed\CategoryStorage\Persistence\CategoryStorageQueryContainerInterface as SprykerCategoryStorageQueryContainerInterface;

interface CategoryStoreStorageQueryContainerInterface extends SprykerCategoryStorageQueryContainerInterface
{
}
